### ISSUE TITLE
A pile of leaves incorrectly changes the color of the biome with Quark

### ISSUE THREAD

**Issue by ghost** [team-abnormals/woodworks#1]
![2022-09-07_18 44 06](https://user-images.githubusercontent.com/85073449/188893811-7c67e10a-e3bd-4830-a553-26251e234b35.png)

**Comment by bageldotjpg** [comment]
I believe you have to add `woodworks:oak_leaf_pile` to the "Leaves List" under Quark's `[client.greener_grass]` section of `quark-common.toml`
