### ISSUE TITLE
New Beehives do not work

### ISSUE THREAD

**Issue by MythrilBagels** [team-abnormals/woodworks#11]
This is in the 1.19 version specifically. I tried making a few Birch Beehives and placed them around my area, but the bees didnt use them, and instead just kept flying around even late into the night. I made a quick creative world to do a more thorough test, placing each of the Hives from this mod and the bees still wouldn't use them. But as soon as I placed a vanilla hive (Nest or Oak), they flew straight inside

**Comment by bageldotjpg** [comment]
This was fixed in the latest version of Blueprint: https://www.curseforge.com/minecraft/mc-mods/blueprint/files/4019850
