### ISSUE TITLE
Chests don't have the guarded by piglins tag

### ISSUE THREAD

**Issue by WitheredWasabi** [team-abnormals/woodworks#15]

**Comment by bageldotjpg** [comment]
Uh... yeah they do: https://github.com/team-abnormals/woodworks/blob/1.19.x/src/generated/resources/data/minecraft/tags/blocks/guarded_by_piglins.json
![image](https://user-images.githubusercontent.com/55970498/215382928-11690829-69a1-41ac-be33-482dc86ef9d5.png)
