### ISSUE TITLE
normal vanilla chests take recipe priority to bormals woodworks chests

### ISSUE THREAD

**Issue by thelegitdolt** [team-abnormals/woodworks#16]

**Comment by bageldotjpg** [comment]
Please put more effort into your issue posts, like proper grammar and real descriptions and images too. This isn't helpful. Nearly every issue you've made is filled with broken spelling, random words, no description, improper grammar, etc.

**Comment by Trexador** [comment]
![2023-02-06_15 33 59](https://user-images.githubusercontent.com/124629875/217080488-f9aade2a-03f6-45c0-b2b6-f3fb17d45ebf.png)
