### ISSUE TITLE
Sawmill transparency Issue

### ISSUE THREAD

**Issue by ClephLeSDF** [team-abnormals/woodworks#17]
(1.18.2 version)
![image](https://user-images.githubusercontent.com/16508989/216820379-74dc0f2a-7303-431f-a925-36c29ddf177b.png)

**Comment by Warhand** [comment]
Came here to post this same issue, and saw that it was already reported.

So I'll just include what I've found, it doesn't seem to be any sort of issue with the model or the texture, which means its probably something to do with the direct code of the block itself, which I'm not as experienced with.

I have also replicated this issue using just Woodworks V 1.2.0, blueprint 5.5.0, forge 40.2.0, and minecraft 1.18.2, so its not a compat problem.
