### ISSUE TITLE
Sawmill recipes do not work when on a Server.

### ISSUE THREAD

**Issue by LaGz4643** [team-abnormals/woodworks#19]
This was tested with only the latest versions of Blueprint and Woodworks installed on both the client and server.

Sawmill recipes work correctly on Singleplayer.

When joining the server and trying to use a sawmill, all recipes do not work. Placing any Log or Planks into the input slot does not give any output items to choose from. Using the /recipe give command with a Woodworks sawing recipe outputs "No new recipes were learned". All other recipes work correctly.

Client logs:
[latest.log](https://github.com/team-abnormals/woodworks/files/10689948/latest.log)

Server logs:
[latest.log](https://github.com/team-abnormals/woodworks/files/10689966/latest.log)

**Comment by pointwoods** [comment]
I also have this same issue, abnormals plz fix
