### ISSUE TITLE
[CRASH] Crash on game launch with mod enabled

### ISSUE THREAD

**Issue by YassaaaTU** [team-abnormals/woodworks#41]
### **Mod Loader**: 
Forge 47.2.18

### **Modpack**: 
CTE2 (but modified with mods that I installed)

### **Minecraft Version**: 
1.20.1

### **Notes**:
what happens? just launch the game and it crashes without finishing loading

### **Crash Report**:
[Crash log](https://mclo.gs/J14KCYY)

**Comment by bageldotjpg** [comment]
Doesn't mention Woodworks. Looks to be caused by `drippyloadingscreen`

**Comment by YassaaaTU** [comment]
So it's `drippyloadingscreen` that is incompatible with Woodworks? 
Cause when I remove/disable Woodworks Minecraft works with no issue and there are no crashes.
And it runs with `drippyloadingscreen`

**Comment by YassaaaTU** [comment]
> Doesn't mention Woodworks. Looks to be caused by `drippyloadingscreen`

So it's `drippyloadingscreen` that is incompatible with Woodworks? 
Cause when I remove/disable Woodworks Minecraft works with no issue and there are no crashes.
And it runs with `drippyloadingscreen`
