### ISSUE TITLE
Woodworks for MC 1.20.1 asking for a version of Blueprint that doesn't exist.

### ISSUE THREAD

**Issue by Joporai124** [team-abnormals/woodworks#42]
So I added Woodworks to my Minecraft game as well as Blueprint and when I try to load up Minecraft it says that it needs Blueprint 7.1.0 or above but the latest version of Blueprint available is 7.0.3.

![2024-04-28_14 01 36](https://github.com/team-abnormals/woodworks/assets/55121806/d1c7ea3a-86fd-4c43-80ba-4a5020800152)

**Comment by bageldotjpg** [comment]
curseforge hasnt approved it for some reason
https://modrinth.com/mod/blueprint/version/7.1.0
