### ISSUE TITLE
[Forge 1.20.1} Mod disables the blocks for Quark's woods with no option to disable it

### ISSUE THREAD

**Issue by vizthex123** [team-abnormals/woodworks#44]
Specifically for Ashen, Azalea, and Trumpet woods.

**Comment by bageldotjpg** [comment]
Turn off the quark setting for auto compat, it disables them

**Comment by vizthex123** [comment]
> Turn off the quark setting for auto compact, it disables them

I can't find such a setting in either config, unless you mean disabling the chests from one mod? I want to keep both types of chests.

**Comment by bageldotjpg** [comment]
It's called anti overlap or something
